# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1f4f2881e9834bd498d4e09e226bbec1"
application_url = "https://example.com"
embedded = true
name = "bundle-box-builder"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions"

[metaobjects.app.build_a_box_builder]
name = "Build a Box Builder"
access.admin = "merchant_read"
access.storefront = "public_read"

[metaobjects.app.build_a_box_builder.fields.name]
name = "Name"
type = "single_line_text_field"

[metaobjects.app.build_a_box_builder.fields.builder_id]
name = "Builder ID"
type = "single_line_text_field"

[metaobjects.app.build_a_box_builder.fields.status]
name = "Status"
type = "single_line_text_field"

[metaobjects.app.build_a_box_builder.fields.thumbnail]
name = "Thumbnail"
type = "file_reference"

[product.metafields.app.build_a_box_builder]
name = "Build a Box Builder"
description = "The Build a Box builder attached to this product."
type = "metaobject_reference<$app:build_a_box_builder>"


[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[app_proxy]
url="/build-a-box-proxy"
prefix="apps"
subpath="build-a-box"
scopes="write_app_proxy"